--CREATE CARDS TABLE


CREATE TABLE T_CARDS(
	CARD_ID VARCHAR(100) PRIMARY KEY,
	CARD_NAME VARCHAR(100),
	CARD_DESCRIPTION VARCHAR(100),
	CARD_COLOR VARCHAR(100),
	CREATE_BY VARCHAR(100),
	CARD_STATUS VARCHAR(50),
	CREATED_ON DATE
)